version: '3.8'

services:
  shareit-server:
    build: shareIt-server
    image: shareit-server-image
    container_name: shareIt-server-container
    ports:
      - "8080:9090"
    depends_on:
      - shareit-db
    environment:
      - SPRING_DRIVER_CLASSNAME=org.postgresql.Driver
      - DB_HOST=shareit-db
      - DB_PORT=5432
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  shareit-db:
    image: postgres:16.2-alpine
    container_name: shareit-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=shareit